/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class personal_chencs_practice_jni_KeyNativeUtils */

#ifndef _Included_personal_chencs_practice_jni_KeyNativeUtils
#define _Included_personal_chencs_practice_jni_KeyNativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     personal_chencs_practice_jni_KeyNativeUtils
 * Method:    getKeyElements
 * Signature: ([B[I[B[I)I
 */
JNIEXPORT jint JNICALL Java_personal_chencs_practice_jni_KeyNativeUtils_getKeyElements
  (JNIEnv *, jclass, jbyteArray, jintArray, jbyteArray, jintArray);

/*
 * Class:     personal_chencs_practice_jni_KeyNativeUtils
 * Method:    getKey
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_personal_chencs_practice_jni_KeyNativeUtils_getKey
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
